server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: hayes-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.11.161:8848
    gateway:
      routes: #配置路由路径
        - id: hayes-cloud-auth-route
          uri: lb://hayes-cloud-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: hayes-cloud-system-route
          uri: lb://hayes-cloud-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写