server:
  port: 5002
spring:
  application:
    name: hayes-cloud-system
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.11.161:8848
logging:
  level:
    root:
      info

